
import javax.swing.table.DefaultTableModel;
import java.math.*;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author bloodphoenix
 */

public class WorldPopulationGUI extends javax.swing.JFrame {

    /**
     * Creates new form WorldPopulationGUI
     */
    public WorldPopulationGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnProceed = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        Year = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        Population = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        TFR = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        pop1 = new javax.swing.JTextField();
        pop2 = new javax.swing.JTextField();
        pop3 = new javax.swing.JTextField();
        Error = new javax.swing.JTextField();
        Autofill = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("World Population Prediction Project");

        btnProceed.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        btnProceed.setText("OK");
        btnProceed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProceedActionPerformed(evt);
            }
        });

        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        btnExit.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        btnExit.setText("EXIT");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Year", "Population", "Change Population", "Growth Rate"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Enter Population details"));
        jPanel1.setLayout(null);

        jLabel7.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        jLabel7.setText("Enter Current Year");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(40, 30, 207, 25);

        Year.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                YearActionPerformed(evt);
            }
        });
        jPanel1.add(Year);
        Year.setBounds(270, 30, 180, 28);

        jLabel1.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        jLabel1.setText("Enter Current year population");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(40, 70, 230, 28);

        Population.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PopulationActionPerformed(evt);
            }
        });
        jPanel1.add(Population);
        Population.setBounds(270, 70, 181, 28);

        jLabel2.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        jLabel2.setText("Enter Total Fertility Rate");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(40, 110, 207, 25);
        jPanel1.add(TFR);
        TFR.setBounds(270, 110, 181, 28);

        jLabel6.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        jLabel6.setText("Enter Percentage of people that are in following age group as of now  :");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(40, 150, 515, 20);

        jLabel3.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        jLabel3.setText("% age ( 0-15 )");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(40, 190, 130, 26);

        jLabel4.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        jLabel4.setText("% age ( 15-49 )");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(180, 190, 130, 29);

        jLabel5.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        jLabel5.setText("% age (49 above )");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(340, 190, 130, 26);

        pop1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pop1ActionPerformed(evt);
            }
        });
        jPanel1.add(pop1);
        pop1.setBounds(40, 220, 91, 28);
        jPanel1.add(pop2);
        pop2.setBounds(190, 220, 91, 28);

        pop3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pop3ActionPerformed(evt);
            }
        });
        jPanel1.add(pop3);
        pop3.setBounds(350, 220, 92, 28);

        Error.setBackground(new java.awt.Color(237, 240, 245));
        Error.setForeground(new java.awt.Color(245, 0, 0));
        Error.setBorder(null);
        Error.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ErrorActionPerformed(evt);
            }
        });
        jPanel1.add(Error);
        Error.setBounds(50, 250, 530, 30);

        Autofill.setText("Auto fill");
        Autofill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AutofillActionPerformed(evt);
            }
        });
        jPanel1.add(Autofill);
        Autofill.setBounds(490, 220, 100, 28);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imageedit_5_9746346097.png"))); // NOI18N
        jPanel1.add(jLabel9);
        jLabel9.setBounds(30, 10, 580, 280);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnProceed, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63)
                        .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                        .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(55, 55, 55))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnProceed)
                    .addComponent(btnClear)
                    .addComponent(btnExit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PopulationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PopulationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PopulationActionPerformed

    private void pop1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pop1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pop1ActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        Population.setText("");
        TFR.setText("");
        pop1.setText("");
        pop2.setText("");
        pop3.setText("");
        Year.setText("");
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        while(model.getRowCount() > 0)
        {
            for(int i=0; i<model.getRowCount(); i++)
            {
                model.removeRow(i);
            }
        }
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnProceedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProceedActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        while(model.getRowCount() > 0)
        {
            for(int i=0; i<model.getRowCount(); i++)
            {
                model.removeRow(i);
            }
        }
        
        long Current_pop=0L,prev_pop=0L;
        float TotalFR=0.0F;
        float pop11=0.0F;
        float pop22=0.0F;
        float pop33=0.0F;
        int year=0;
        int err=0;
        
        try{
        Current_pop = Long.parseLong(Population.getText());
        TotalFR = Float.parseFloat(TFR.getText());
        pop11 = Float.parseFloat(pop1.getText());
        pop22 = Float.parseFloat(pop2.getText());
        pop33 = Float.parseFloat(pop3.getText());
        year = Integer.parseInt(Year.getText());
        }
         catch(NumberFormatException e)
                {
                    err = -1;
                }
        
        if(err==0)
        {
            if((pop11+pop22+pop33) !=100.0F)
            {
                Error.setText("The sum of percentages is not 100!");
            }
        
            else if(TotalFR<=0.0)
            {
                Error.setText("Fertility Rate cannot be 0 or negative!");
            }
            else if(Current_pop<=0L)
            {
                Error.setText("Population cannot be 0 or negative!");
            }
            else if(year<=0L)
            {
                Error.setText("Year cannot be 0 or negative!");
            }
            else if(Current_pop>=11000000000L)
            {
                Error.setText("Population cannot Greater than 11 Billion!");
            }
            else
            {
            
                Error.setText("");
                TotalFR = (float)(((pop22/100)*TotalFR + TotalFR)*0.85);
                if(Current_pop < 50000)
                TotalFR++;
                for(int i=year+1; i<year+76; i++)
                {
                    prev_pop = Current_pop;
                    Current_pop = (long) (Current_pop*Math.exp((TotalFR-2.0)/100));
                    if(Current_pop >= 11000000000L)
                    Current_pop = prev_pop;
                    TotalFR = (float)(TotalFR-TotalFR*0.005);
                    if(TotalFR <= 0.5)
                    TotalFR = (float)0.5;
                    
                    model.addRow(new Object[] {String.valueOf(i),String.valueOf(Current_pop),String.valueOf(Current_pop-prev_pop),String.valueOf(TotalFR-2.0)});
        
                }
            }
        }
        else
        {
            Error.setText("No feild can be empty!!");
        }

    }//GEN-LAST:event_btnProceedActionPerformed

    private void pop3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pop3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pop3ActionPerformed

    private void YearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_YearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_YearActionPerformed

    private void AutofillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AutofillActionPerformed
        // TODO add your handling code here:
        pop1.setText("22.3");
        pop2.setText("46.2");
        pop3.setText("31.5");
    }//GEN-LAST:event_AutofillActionPerformed

    private void ErrorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ErrorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ErrorActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WorldPopulationGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WorldPopulationGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WorldPopulationGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WorldPopulationGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WorldPopulationGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Autofill;
    private javax.swing.JTextField Error;
    private javax.swing.JTextField Population;
    private javax.swing.JTextField TFR;
    private javax.swing.JTextField Year;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnProceed;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField pop1;
    private javax.swing.JTextField pop2;
    private javax.swing.JTextField pop3;
    // End of variables declaration//GEN-END:variables
}
